const messages = {
  warning: "Warnung",
  error: "Fehler",
  node: "benötigt node.js",
  _new: "neu",
  _and: "und",
  yes: "ja",
  no: "nein",
  chars: "Buchstaben",
  need: "Du benötigst",
  missing: "fehlt bei",
  eg: "z.B.",
  welcome: "Willkommen zum",
  thanks: "Dank Dir",
  comeback: "Bis bald!",
  bye: "Tschö!",
  startServer: "Starte den Server so: > PW='yourpasswordhere' node server",
  noAgain: "Nein. Lass es mich nochmal versuchen.",
  unknown: "Ein unbekannter Fehler trat auf. Etwas lief schrecklich schief. Entschuldigung!",

  cInstalled: "Fantastisch. Du hast IndieAuth installiert",
  cCredDir: "Wir haben den Ordner angelegt um Deine Zugangsdaten zu speichern:",
  cPWnote1: "Im nächsten Schritt legst Du ein Passwort für den IndieAuth-Server fest.",
  cPWnote2: "  Das Passwort wird benötigt um die Zugangsdaten zu verschlüsseln !",
  cPWnote3: "Such Dir ein echt starkes Passwort aus ...",
  cPWerr: "Sorry. Die Passworte sind verschieden.",
  cWriteErr: "Sorry. Es scheint, wir können in dem Ordner, den wir gerade erstellt haben, nicht speichern.",
  cWriteHint: "Stelle sicher, daß _{directory} beschreibbar ist für \"_{user}\"",
  cNoPWerr: "Sorry. Du hast keine \"PW\" Umgebungsvariable angegeben, als Du den IndieAuth Server gestartet hast !",
  cNoPWerr2: "Starte den Server so: 'PW=\"MEINSuperPasswortHIER\" node server'",
  cCLI: "Möchtest Du die IndieAuth CLI starten?",
  cWorks: "Funktioniert perfekt. Du kannst jetzt alle Credentials für IndieAuth verwalten.",
  cFoundCred: "Bekannte Provider Zugangsdaten gefunden",
  cFoundNot: "Noch nicht installiert",
  cFoundAll: "Alle Provider installiert",

  qWhat: "Was ist der Wert für ",
  qPw: "Wie lautet Dein Passwort ?",
  qPwConfirmed: "Gib Dein Passwort zur Bestätigung erneut ein:",
  qAction: "Was möchtest Du tun ?",
  qaCreate: "Erstelle neue Zugangsdaten",
  qsCreate: "Neue Zugangsdaten",
  qaEdit: "Bearbeite existierende Zugangsdaten",
  qsEdit: "Bearbeite Zugangsdaten",
  qaQuit: "Beenden",
  qaNewP: "Neuer (unbekannter) Provider",
  qProviderID: "Für welche Provider API möchtest Du Zugangsdaten erstellen ?",
  qproviderIDtba: "Wie soll der Provider heissen ?",
  qCanHelp: "Können wir helfen, Zugangsdaten zu sammeln für",
  qcHelp: "Ja, bitte helft.",
  qcNoHelp: "Nein, ich habe die Zugangsdaten.",
  qcHelpGet: "Bekomme die Daten auf",
  qcOpenPage: "Öffne die Entwicklerseite.",
  qsOpenPage: "Öffnen der Webseite ...",
  qcGoOn: "Weiter, ich habe die Zugangsdaten.",
  qApiKey: "Wie ist dein 'API key' ? (zusätzlicher Provider Parameter)",
  qMail: "Wie lautet die eMail Adresse von der wir senden ?",
  qName: "Wer soll als Absender angezeigt werden ?",
  qHost: "Welcher SMTP host wird benutzt ?",
  qHostNote: "Achtung: Könnte vom eMail-Adressen-Host abweichen. Siehe Provider docs ...",
  qPort: "Welcher SMTP port wird benutzt @",
  qNote: "Möchtest Du eine kurze Notiz in den Zugangsdaten hinterlassen, nur für Dich ?",
  qNoNote: "Nö, alles gut!",
  qeProviderID: "Welchen Provider möchtest Du bearbeiten ?",
  qProviderEdit: "Was möchtest Du ändern ?",
  qeKS: "Key und Secret",
  qsKS: "Zugangsdaten",
  qeAll: "Beliebige Eigenschaften",
  qsAll: "beliebig",
  qeAdd: "Eigenschaft hinzufügen",
  qsAdd: "Eigenschaft hinzufügen",
  qeNo: "Nichts",
  qProviderAddKey: "Welche Eigenschaft sollen wir hinzufügen ?",
  qProviderAddValue: "Was ist der Wert für",
  qProviderAddAnother: "Add another property ?",
  qProviderNewValue: "Was ist der neue Wert für",
  vPW1: "Sorry, dieses Häppchen ist viel zu klein",
  vPW2: "Sorry, Passwort ist ein wenig zu schwach",
  vPW: "Dein Passwort",
  vSc: "erzielt",
  vLength: "Der Wert für _{key} muss mindestens _{length} Buchstaben lang sein.",
  vMaxLength: "Der Wert für _{key} darf nicht länger als _{length} Buchstaben sein.",
  vNoCred: "Konnte keine Zugangsdaten finden.",
  vNotFoundCred: "Konnte einige Zugangsdaten nicht finden",
  vInvalidCred: "Einige Zugangsdaten waren ungültig",
  vHintCred: "Starte das Command Line Utility (CLI) um Details anzuzeigen und sie zu erstellen.",
  vWrongPw: "Konnte das Passwort nicht verifizieren.",
  vExistsP: "Sorry. Ein Provider mit diesem Namen ist schon installiert.\nWähle einen anderen Namen.",
  vPrimaryP: "Sorry. Dies ist ein reservierter Name eines IndieAuth Providers.\nFüge ein suffix zu.",
  vEmail: "Das sieht nicht wie eine gültige Adresse aus.",
  vAddKey: "Dies ist eine readOnly Eigenschaft."
};

export default messages;
